version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current/
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: root
